# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'moverui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(603, 651)
        MainWindow.setStyleSheet("background-color: #181e23;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushUP10 = QtWidgets.QPushButton(self.centralwidget)
        self.pushUP10.setGeometry(QtCore.QRect(240, 0, 121, 121))
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(48)
        self.pushUP10.setFont(font)
        self.pushUP10.setStyleSheet("border: 10px solid grey; \n"
"background-color: #aabbcc;\n"
"border-radius: 50px;")
        self.pushUP10.setObjectName("pushUP10")
        self.pushUP1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushUP1.setGeometry(QtCore.QRect(240, 130, 121, 121))
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(48)
        self.pushUP1.setFont(font)
        self.pushUP1.setStyleSheet("border: 10px solid grey; \n"
"background-color: #aabbcc;\n"
"border-radius: 50px;")
        self.pushUP1.setObjectName("pushUP1")
        self.pushDOWN10 = QtWidgets.QPushButton(self.centralwidget)
        self.pushDOWN10.setGeometry(QtCore.QRect(240, 480, 121, 121))
        font = QtGui.QFont()
        font.setPointSize(48)
        self.pushDOWN10.setFont(font)
        self.pushDOWN10.setStyleSheet("border: 10px solid grey; \n"
"background-color: #aabbcc;\n"
"border-radius: 50px;")
        self.pushDOWN10.setObjectName("pushDOWN10")
        self.pushDOWN1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushDOWN1.setGeometry(QtCore.QRect(240, 350, 121, 121))
        font = QtGui.QFont()
        font.setPointSize(48)
        self.pushDOWN1.setFont(font)
        self.pushDOWN1.setStyleSheet("border: 10px solid grey; \n"
"background-color: #aabbcc;\n"
"border-radius: 50px;")
        self.pushDOWN1.setObjectName("pushDOWN1")
        self.pushLEFT10 = QtWidgets.QPushButton(self.centralwidget)
        self.pushLEFT10.setGeometry(QtCore.QRect(0, 240, 121, 121))
        font = QtGui.QFont()
        font.setPointSize(48)
        self.pushLEFT10.setFont(font)
        self.pushLEFT10.setStyleSheet("border: 10px solid grey; \n"
"background-color: #aabbcc;\n"
"border-radius: 50px;")
        self.pushLEFT10.setObjectName("pushLEFT10")
        self.pushLEFT1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushLEFT1.setGeometry(QtCore.QRect(130, 240, 121, 121))
        font = QtGui.QFont()
        font.setPointSize(48)
        self.pushLEFT1.setFont(font)
        self.pushLEFT1.setStyleSheet("border: 10px solid grey; \n"
"background-color: #aabbcc;\n"
"border-radius: 50px;")
        self.pushLEFT1.setObjectName("pushLEFT1")
        self.pushRIGHT1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushRIGHT1.setGeometry(QtCore.QRect(350, 240, 121, 121))
        font = QtGui.QFont()
        font.setPointSize(48)
        self.pushRIGHT1.setFont(font)
        self.pushRIGHT1.setStyleSheet("border: 10px solid grey; \n"
"background-color: #aabbcc;\n"
"border-radius: 50px;")
        self.pushRIGHT1.setObjectName("pushRIGHT1")
        self.pushRIGHT10 = QtWidgets.QPushButton(self.centralwidget)
        self.pushRIGHT10.setGeometry(QtCore.QRect(480, 240, 121, 121))
        font = QtGui.QFont()
        font.setPointSize(48)
        self.pushRIGHT10.setFont(font)
        self.pushRIGHT10.setStyleSheet("border: 10px solid grey; \n"
"background-color: #aabbcc;\n"
"border-radius: 50px;")
        self.pushRIGHT10.setObjectName("pushRIGHT10")
        self.pushClose = QtWidgets.QPushButton(self.centralwidget)
        self.pushClose.setGeometry(QtCore.QRect(10, 0, 101, 101))
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(48)
        self.pushClose.setFont(font)
        self.pushClose.setStyleSheet("border: 10px solid grey; \n"
"background-color: #cc7777;\n"
"border-radius: 50px;")
        self.pushClose.setObjectName("pushClose")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 603, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushUP10.setText(_translate("MainWindow", "10"))
        self.pushUP1.setText(_translate("MainWindow", "1"))
        self.pushDOWN10.setText(_translate("MainWindow", "10"))
        self.pushDOWN1.setText(_translate("MainWindow", "1"))
        self.pushLEFT10.setText(_translate("MainWindow", "10"))
        self.pushLEFT1.setText(_translate("MainWindow", "1"))
        self.pushRIGHT1.setText(_translate("MainWindow", "1"))
        self.pushRIGHT10.setText(_translate("MainWindow", "10"))
        self.pushClose.setText(_translate("MainWindow", "X"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
